- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.20.0
  hooks:
    - id: yamllint
      files: \.(yaml|yml)$
- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.2.0
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
