---
- name: Manage Manjaro Linux Server
  hosts: manjaro_hosts
  order: sorted
  vars:
    pacman_pkgs:
      - adobe-source-han-sans-jp-fonts
      - adobe-source-han-serif-jp-fonts
      - ansible
      - docker
      - docker-compose
      - noto-fonts-cjk
    awx_version: "9.0.1"
    netbox_version: "v2.6.7"
  tasks:
    - name: set timezone
      timezone:
        name: "Asia/Tokyo"
        hwclock: UTC
      become: yes
    - name: install packages with pacman
      pacman:
        name: "{{ pacman_pkgs }}"
        state: present
      become: yes
    - name: enable docker service
      systemd:
        name: docker
        enabled: yes
        state: started
      become: yes
    - name: clone awx repo
      git:
        repo: https://github.com/ansible/awx.git
        version: "{{ awx_version }}"
        dest: ~/awx
        clone: yes
      register: awx_clone_result
    - name: install awx
      command: ansible-playbook -i inventory install.yml
      args:
        chdir: "~{{ ansible_user }}/awx/installer"
      become: yes
      when: awx_clone_result.changed
    - name: clone netbox repo
      git:
        repo: https://github.com/netbox-community/netbox-docker.git
        dest: ~/netbox-docker
        clone: yes
      register: netbox_clone_result
    - name: pull netbox containers and start
      docker_service:
        project_src: "~{{ ansible_user }}/netbox-docker"
        pull: yes
        state: present
      become: yes
      environment:
        VERSION: "{{ netbox_version }}"
      when: netbox_clone_result.changed
