# Install Netbox
- name: Install Netbox
  hosts: netbox_hosts
  vars:
    pacman_pkgs:
      - docker
      - docker-compose
      - git
  tasks:
    - name: install packages with pacman
      pacman:
        name: "{{ pacman_pkgs }}"
        state: present
      become: yes
    - name: install Netbox
      import_role:
        name: netbox
