---
# tasks file for awx
- name: clone awx repo
  git:
    repo: "{{ awx_url }}"
    version: "{{ awx_version }}"
    dest: ~/awx
    clone: yes
  register: awx_clone_result
- name: install awx
  command: ansible-playbook -i inventory install.yml
  args:
    chdir: "~{{ ansible_user }}/awx/installer"
  become: yes
  notify: "restart awx"
  when: awx_clone_result.changed|bool
