---
# tasks file for awx
- name: enable docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes
- name: clone AWX repo
  git:
    repo: "{{ awx_url }}"
    version: "{{ awx_version }}"
    dest: "{{ ansible_user_dir }}/awx"
    clone: yes
  register: awx_clone_result
- name: install AWX
  command: ansible-playbook -i inventory install.yml
  args:
    chdir: "{{ ansible_user_dir }}/awx/installer"
  become: yes
  when: awx_clone_result.changed|bool
  notify: "restart AWX"
