---
# tasks file for netbox
- name: clone netbox-docker repo
  git:
    repo: "https://github.com/netbox-community/netbox-docker.git"
    dest: "{{ ansible_user_dir }}/netbox-docker"
    version: release
- name: copy docker-compose.override.yml
  template:
    src: docker-compose.override.yml.j2
    dest: "{{ ansible_user_dir }}/netbox-docker/docker-compose.override.yml"
    backup: yes
- name: pull latest image & start Netbox containers
  docker_compose:
    project_src: "{{ ansible_user_dir }}/netbox-docker"
    pull: yes
    recreate: smart
    state: present
  environment:
    VERSION: "{{ netbox_version }}"
  become: yes
- name: copy backup script
  template:
    src: templates/backup_netbox.sh.j2
    dest: /usr/local/bin/backup_netbox.sh
    mode: 0700
  become: yes
- name: set daily backup
  cron:
    name: backup Netbox DB daily
    job: "/usr/local/bin/backup_netbox.sh > /tmp/backup_netbox.out 2>&1"
    hour: "0"
    minute: "0"
    state: present
  become: yes
